thresholds:
  yoy: -0.12
  delta: -250000
  slope: -1.5
notification:
  email:
    subject: "売上アラート通知"
    from: "noreply@example.com"
    to: "owner@example.com"
    host: "smtp.example.com"
    port: 587
    use_tls: true
  slack:
    webhook: "https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX"
